### ISSUE TITLE
Refactor Code to Reduce Code Duplication by Creating Custom Widgets

### ISSUE THREAD

**Issue by Priyammm05** [avishka2k/find_food_application#9]
**Issue Description:**
In our codebase, there are several instances where we have repeated code segments that perform similar tasks. This redundancy not only makes the code harder to maintain but also increases the chances of introducing bugs when making changes. To improve code maintainability and readability, we should consider creating custom widgets/components to encapsulate these common functionalities.

**Proposed Solution:**
To address this issue, we should identify the repeated code segments and refactor them into custom widgets. These widgets can then be reused throughout the codebase wherever the same functionality is needed. By doing so, we can achieve the following benefits:

- Eliminate code duplication, reducing the risk of errors and making future changes easier.
- Improve code readability by abstracting complex logic into well-named and well-documented custom widgets.
- Enhance maintainability by centralizing updates and fixes within the custom widgets.

**Comment by Priyammm05** [comment]
Can I work on this for hacktoberfest @avishka2k

**Comment by avixkap** [comment]
Hi @Priyammm05 

We moved this project to another place before, but If you want to contribute to hacktomberfest you can do it.

Thanks.

**Comment by Priyammm05** [comment]
Sure can you please assign it to me

**Comment by avixkap** [comment]
done

**Comment by Priyammm05** [comment]
I think the most of the code and packages had been moved from this code base but still I have like created a custom textfield to reduce some duplication.
